---
- name: Add GitLab repository key
  apt_key:
    url: "{{ gitlab_runner_apt_key_url }}"
    state: present

- name: Remove old GitLab APT repo
  apt_repository:
    repo: "{{ item }}"
    mode: "0644"
    update_cache: yes
    state: absent
  with_items: "{{ gitlab_runner_apt_old_repos }}"

- name: Add new GitLab APT repo
  apt_repository:
    repo: "{{ item }}"
    mode: "0644"
    update_cache: yes
    state: present
  with_items: "{{ gitlab_runner_apt_repos }}"

- name: Remove old GitLab Runner
  apt:
    name: gitlab-ci-multi-runner
    state: absent
    update_cache: yes
    cache_valid_time: 1800
  register: oldrun

- name: Install new GitLab Runner
  apt:
    name: gitlab-runner
    state: present
    update_cache: yes
    cache_valid_time: 1800
  register: newrun

- name: Fixup upgrade
  command: /usr/share/gitlab-runner/post-install
  when: oldrun.changed and newrun.changed

- name: Register new runners
  include: register-runner.yml
  with_items: "{{ gitlab_runner.runners | default([]) }}"

- name: Adjust concurrent build count
  lineinfile:
    dest: "/etc/gitlab-runner/config.toml"
    regexp: '^concurrent = (\d+)$'
    line: 'concurrent = {{ gitlab_runner.concurrent_builds }}'
    state: present
  notify: reload config
